config {
  type: 'table',
  schema: 'dwh',
  name: 'dim_final_rate',
  description: 'The final rate in effect at the end of the trip',
  columns: {
    rate_code_id: 'Unique identifier of the final rate',
    rate_name: 'Rate name',
  }
}

SELECT 1 AS rate_code_id, 'Standard rate' AS rate_name
UNION ALL
SELECT 2, 'JFK'
UNION ALL
SELECT 3, 'Newark'
UNION ALL
SELECT 4, 'Nassau or Westchester'
UNION ALL
SELECT 5, 'Negotiated fare'
UNION ALL
SELECT 99, 'Null/unknown'
